- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copy expense config file
  ansible.builtin.template:
    path: /etc/nginx/default.d/expense.conf

- name: Remove file content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: present


- name: Create application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: present


- name: download application content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Restart systemd service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
